In [1]:
import numpy as np
import pandas as pd

In [66]:
data = pd.read_csv("Resources/cleaning.csv")

C:\Users\alana\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [67]:
data = data.drop(columns=['Unnamed: 0'])

In [8]:
data.posit.unique()

array(['P', 'SS', '2B', 'OF', '3B-2B', '2B-3B', 'SS-2B', '3B', 'OF-1B',
       'C', 'OF-2B', '2B-OF', '1B', 'UTL', 'C-1B', '3B-C', 'C-3B',
       '3B-SS', 'IF', 'OF-3B', 'OF-P', 'SS-3B', '1B-OF', '3B-OF', '1B-P',
       'P-C', 'P-OF', '2B-SS', '2B-P', '3B-1B', 'P-1B', 'OF-C', '1B-3B',
       'P-3B', 'C-OF', '1B-C', 'P-IF', 'OF-SS', '3B-P', 'SS-OF', '2B-C',
       'SS-P', 'H', nan, 'LF', 'P-2B', 'C-2B', 'C-P', 'RF', 'CF', 'RF-LF',
       'LF-CF', 'LF-RF', 'LF-2B', '2B-LF', 'CF-RF', 'OF-DH', '1B-LF',
       'CF-LF', 'LF-1B', '1B-DH', 'LF-OF', '1B-2B', 'DH', 'C-DH', 'RF-CF',
       'RF-OF', 'DH-OF', 'DH-CF', '2B-CF', 'RF-1B', 'DH-1B', 'SS-CF',
       'CF-OF', '1B-RF', '1B-SS', 'DH-3B', 'C-IF', '3B-LF', 'CF-3B',
       '2B-1B', 'RF-3B', 'IF-P', 'CF-2B', '3B-RF', 'SS-1B', 'IF-C',
       'SS-C', 'LF-C', '3B-DH', 'SS-LF', 'INF', 'RF-2B', 'C-LF', 'P-SS',
       'CF-1B', 'C-SS', 'LF-SS', 'C-RF', '3B-CF', 'P-DH', '2B-RF',
       'LF-3B', 'CF-SS', 'SS-RF', 'DH-LF', 'RF-P', 'DH-C', 'P-LF', 'UT-P',
       'LF-DH', 'RF-C'], dtype=object)

In [12]:
positAdjuster = {'P' : 0, 'SS': 7.5, '2B': 2.5, 'OF': -7.5, '3B-2B': 2.5, '2B-3B': 2.5, 'SS-2B': 7.5, '3B': 2.5, 'OF-1B': -7.5,
'C': 12.5, 'OF-2B': 2.5, '2B-OF': 2.5, '1B': -12.5, 'UTL': 0, 'C-1B': 12.5, '3B-C': 12.5, 'C-3B': 12.5,
'3B-SS': 7.5, 'IF': 2.5, 'OF-3B': 2.5, 'OF-P': -7.5, 'SS-3B': 7.5, '1B-OF': -7.5, '3B-OF': 2.5, '1B-P': -12.5,
'P-C': 12.5, 'P-OF': -7.5, '2B-SS': 7.5, '2B-P': 2.5, '3B-1B': 2.5, 'P-1B': -12.5, 'OF-C': 12.5, '1B-3B': 2.5,
'P-3B': 2.5, 'C-OF': 12.5, '1B-C': 12.5, 'P-IF': 2.5, 'OF-SS': 7.5, '3B-P': 2.5, 'SS-OF': 7.5, '2B-C': 12.5,
'SS-P': 7.5, 'H': 0, 'LF': -7.5, 'P-2B': 2.5, 'C-2B': 12.5, 'C-P': 12.5, 'RF': -7.5, 'CF': 2.5, 'RF-LF': -7.5,
'LF-CF': 2.5, 'LF-RF': -7.5, 'LF-2B': 2.5, '2B-LF': 2.5, 'CF-RF': 2.5, 'OF-DH': -7.5, '1B-LF': -7.5,
'CF-LF': 2.5, 'LF-1B': -7.5, '1B-DH': -12.5, 'LF-OF': -7.5, '1B-2B': 2.5, 'DH': -17.5, 'C-DH': 12.5, 'RF-CF': -7.5,
'RF-OF': -7.5, 'DH-OF': -7.5, 'DH-CF': 2.5, '2B-CF': 2.5, 'RF-1B': -7.5, 'DH-1B': -12.5, 'SS-CF': 7.5,
'CF-OF': 2.5, '1B-RF': -7.5, '1B-SS': 7.5, 'DH-3B': 2.5, 'C-IF': 12.5, '3B-LF': 2.5, 'CF-3B': 2.5,
'2B-1B': 2.5, 'RF-3B': 2.5, 'IF-P': 2.5, 'CF-2B': 2.5, '3B-RF': 2.5, 'SS-1B': 7.5, 'IF-C': 12.5,
'SS-C': 12.5, 'LF-C': 12.5, '3B-DH': 2.5, 'SS-LF': 7.5, 'INF': 2.5, 'RF-2B': 2.5, 'C-LF': 12.5, 'P-SS': 7.5,
'CF-1B': 2.5, 'C-SS': 12.5, 'LF-SS': 7.5, 'C-RF': 12.5, '3B-CF': 2.5, 'P-DH': -17.5, '2B-RF': 2.5,
'LF-3B': 2.5, 'CF-SS': 7.5, 'SS-RF': 7.5, 'DH-LF': -7.5, 'RF-P': -7.5, 'DH-C': 12.5, 'P-LF': -7.5, 'UT-P': 0,
'LF-DH': -7.5, 'RF-C': 12.5}

In [13]:
data['Def'] = data.posit

In [15]:
data = data.replace({"Def" : positAdjuster})

In [91]:
data['SB%'] = data['SB%'].fillna(0)

In [92]:
qual = data[data['PA'] > 0]

In [187]:
data.iloc[64325, data.columns.get_loc('posit')] = "SS"

In [126]:
data.posit = data.posit.replace(['PF-3B'],'OF-3B')

In [84]:
data[data.index == 101474]

,playerid,year,teamName,League,Level,orgName,lastName,firstName,G,AB,...,Age,HT,WT,Bats,Throws,posit,borndate,cityName,regionID,mlbid
101474,16026,1997,Buffalo,Amer,AAA,CLE,Norman,Les,118,428.0,...,28.0,6-1,185,R,R,RF,2/25/1969,Warren,MI,119839.0

In [53]:
data.to_csv("Resources/cleaning.csv")

In [90]:
# Add some of our favorite rate stats
data['PA'] = data.AB + data.BB + data.IBB + data.HBP + data.SF + data.SH
data['ISO'] = data.Slg - data.Bavg
data['BB%'] = data.BB / data.PA
data['K%'] = data.SO / data.PA
data['SB%'] = data.SB / (data.SB + data.CS)
data['BABIP'] = (data.H - data.HR) / (data.AB - data.SO - data.HR + data.SF)

In [93]:
look = qual.groupby(['League', 'Level', 'year']).transform(lambda x: (x - x.mean()) / x.std())

In [87]:
qual.columns

Index(['playerid', 'year', 'teamName', 'League', 'Level', 'orgName',
       'lastName', 'firstName', 'G', 'AB', 'R', 'H', 'Dbl', 'Tpl', 'HR', 'RBI',
       'SB', 'CS', 'BB', 'IBB', 'SO', 'SH', 'SF', 'HBP', 'GDP', 'Bavg', 'Slg',
       'obp', 'OPS', 'Age', 'StartSeason', 'DaysOld', 'HT', 'WT', 'Bats',
       'Throws', 'posit', 'borndate', 'cityName', 'regionID', 'mlbid', 'Def',
       'PA', 'ISO', 'BB%', 'K%', 'SB%'],
      dtype='object')

In [94]:
look.columns

Index(['playerid', 'G', 'AB', 'R', 'H', 'Dbl', 'Tpl', 'HR', 'RBI', 'SB', 'CS',
       'BB', 'IBB', 'SO', 'SH', 'SF', 'HBP', 'GDP', 'Bavg', 'Slg', 'obp',
       'OPS', 'Age', 'HT', 'WT', 'mlbid', 'Def', 'PA', 'ISO', 'BB%', 'K%',
       'SB%', 'BABIP'],
      dtype='object')

In [110]:
final = qual[['playerid', 'year', 'teamName', 'League', 'Level', 'orgName',
       'lastName', 'firstName', 'StartSeason', 'Bats', 'Throws', 'posit', 'borndate',
        'cityName', 'regionID', 'mlbid', 'PA']]

In [111]:
final[['AVG', 'SLG', 'OBP', 'OPS', 'Age', 'HT', 'WT', 'DEF', 'ISO', 'BB%', 'K%', 'SB%', 'BABIP']] = look[['Bavg', 'Slg', 'obp', 'OPS', 'Age', 'HT', 'WT', 'Def', 'ISO', 'BB%', 'K%', 'SB%', 'BABIP']]

In [100]:
final.head()

,playerid,year,teamName,League,Level,orgName,lastName,firstName,Bavg,Slg,...,OBP,Age,HT,WT,DEF,ISO,BB%,K%,SB%,BABIP
0,1509,1988,Charlotte,FSL,A+,TEX,Paula,Julio,0.188,0.217,...,-0.173625,-4.308749,0.175194,-0.799381,-0.083319,-0.718120,0.348925,-0.379131,-1.175085,-0.433280
1,1509,1983,Columbia,SAL,A,NYN,Paula,Julio,0.306,0.450,...,0.735614,-1.802819,0.196412,-0.716121,-0.073184,0.748119,0.052929,-0.307514,-0.653042,0.712601
2,1509,1979,Dunedin,FSL,A+,TOR,Paula,Julio,0.269,0.346,...,0.033933,-1.834079,0.098424,-0.621294,-0.006800,0.469806,-0.872160,0.861451,-1.165969,1.102152
3,1509,1981,Florence,SAL,A,TOR,Paula,Julio,0.248,0.333,...,-0.050862,-1.572849,0.187421,-0.947450,-0.054371,-0.026401,-0.383940,-0.475883,0.820667,0.049430
4,1509,1981,Kinston,Caro,A+,TOR,Paula,Julio,0.266,0.320,...,0.428366,-1.304196,0.155261,-0.508577,-0.111198,-0.776886,0.304452,-0.560480,0.530713,0.157778

In [103]:
final.to_csv("Resources/working.csv")

In [104]:
final.Level.unique()

array(['A+', 'A', 'Rk', 'A-', 'AAA', 'AA'], dtype=object)

In [139]:
leveler = {'A+':3, 'A': 4, 'Rk':6, 'A-':5, 'AAA': 1, 'AA':2}
releveler = {3:'A+', 4:'A', 6:'Rk', 5:'A-', 1: 'AAA', 2 : 'AA'}

In [112]:
final['Top'] = final.Level
final = final.replace({"Level" : leveler})

C:\Users\alana\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [113]:
final.head()

,playerid,year,teamName,League,Level,orgName,lastName,firstName,StartSeason,Bats,...,Age,HT,WT,DEF,ISO,BB%,K%,SB%,BABIP,Top
0,1509,1988,Charlotte,FSL,3,TEX,Paula,Julio,4/1/1988,B,...,-4.308749,0.175194,-0.799381,-0.083319,-0.718120,0.348925,-0.379131,-1.175085,-0.433280,A+
1,1509,1983,Columbia,SAL,4,NYN,Paula,Julio,4/1/1983,B,...,-1.802819,0.196412,-0.716121,-0.073184,0.748119,0.052929,-0.307514,-0.653042,0.712601,A
2,1509,1979,Dunedin,FSL,3,TOR,Paula,Julio,4/1/1979,B,...,-1.834079,0.098424,-0.621294,-0.006800,0.469806,-0.872160,0.861451,-1.165969,1.102152,A+
3,1509,1981,Florence,SAL,4,TOR,Paula,Julio,4/1/1981,B,...,-1.572849,0.187421,-0.947450,-0.054371,-0.026401,-0.383940,-0.475883,0.820667,0.049430,A
4,1509,1981,Kinston,Caro,3,TOR,Paula,Julio,4/1/1981,B,...,-1.304196,0.155261,-0.508577,-0.111198,-0.776886,0.304452,-0.560480,0.530713,0.157778,A+

In [150]:
looker = final[['playerid', 'Level', 'Top']]

In [151]:
looker = looker.groupby('playerid').min()

In [152]:
looker = looker.reset_index()

In [153]:
looker[looker.playerid == 1509]

      playerid  Level Top
1161      1509      3   A

In [154]:
looker = looker.drop(columns = ['Top'])
looker = looker.replace({"Level" : releveler})

In [155]:
final2 = final.merge(looker, on='playerid', how='left')

In [158]:
final2 = final2.rename(columns={'Level_x': 'Level'})

,playerid,year,teamName,League,Level,orgName,lastName,firstName,StartSeason,Bats,...,HT,WT,DEF,ISO,BB%,K%,SB%,BABIP,Top,MaxLevel
0,1509,1988,Charlotte,FSL,3,TEX,Paula,Julio,4/1/1988,B,...,0.175194,-0.799381,-0.083319,-0.718120,0.348925,-0.379131,-1.175085,-0.433280,A+,A+
1,1509,1983,Columbia,SAL,4,NYN,Paula,Julio,4/1/1983,B,...,0.196412,-0.716121,-0.073184,0.748119,0.052929,-0.307514,-0.653042,0.712601,A,A+
2,1509,1979,Dunedin,FSL,3,TOR,Paula,Julio,4/1/1979,B,...,0.098424,-0.621294,-0.006800,0.469806,-0.872160,0.861451,-1.165969,1.102152,A+,A+
3,1509,1981,Florence,SAL,4,TOR,Paula,Julio,4/1/1981,B,...,0.187421,-0.947450,-0.054371,-0.026401,-0.383940,-0.475883,0.820667,0.049430,A,A+
4,1509,1981,Kinston,Caro,3,TOR,Paula,Julio,4/1/1981,B,...,0.155261,-0.508577,-0.111198,-0.776886,0.304452,-0.560480,0.530713,0.157778,A+,A+
5,1509,1980,Kinston,Caro,3,TOR,Paula,Julio,4/1/1980,B,...,0.144464,-0.432508,-0.079024,-0.578399,-0.422233,-0.439732,0.142506,-0.214249,A+,A+
6,1509,1983,Lynchburg,Caro,3,NYN,Paula,Julio,4/1/1983,B,...,0.128234,-0.980189,0.009875,-0.202337,-0.104506,-0.021353,0.552409,-0.228741,A+,A+
7,1509,1984,Lynchburg,Caro,3,NYN,Paula,Julio,4/1/1984,B,...,-0.029099,-1.548520,-0.052299,0.118331,0.368010,-0.577322,0.984801,0.283846,A+,A+
8,1509,1979,Medicine Hat,Pio,6,TOR,Paula,Julio,4/1/1979,B,...,0.135256,-0.500132,0.013833,0.244150,-0.072461,-0.058520,0.686709,0.471467,Rk,A+
9,1509,1979,Utica,NYPL,5,TOR,Paula,Julio,4/1/1979,B,...,0.200746,-0.320442,0.008682,-0.938448,-0.521365,0.540641,1.080150,1.200709,A-,A+
10,1660,1998,Helena,Pio,6,MIL,DiPrima,Giancarlo,4/1/1998,R,...,-2.432042,-1.920126,0.940753,-0.801214,0.036425,-1.222340,0.739952,-0.166576,Rk,Rk
11,1702,1980,GCL Pirates,GCL,6,PIT,Acosta,Ed,4/1/1980,R,...,-0.139893,-0.239188,0.297395,-0.840440,-1.100402,0.028921,-0.168865,0.121680,Rk,Rk
12,1702,1981,GCL Pirates,GCL,6,PIT,Acosta,Ed,4/1/1981,R,...,-0.012342,-0.148988,0.347624,-1.030124,-1.401098,-1.234044,-1.463514,-0.166628,Rk,Rk
13,1765,1996,GCL Devil Rays,GCL,6,TBA,Gonzalez,Milciadez,4/1/1996,R,...,-15.592548,-0.866663,-0.794966,-0.892610,0.112417,0.554708,1.281872,-2.195400,Rk,Rk
14,1916,1996,Azl Rockies,Ariz,6,COL,Hudde,Alejandro,4/1/1996,R,...,0.089245,0.496784,0.293473,-0.321810,-1.165492,0.196895,1.263278,-0.243830,Rk,Rk
15,1962,1996,Butte,Pio,6,TBA,Martinez,Leonardo,4/1/1996,B,...,0.121706,-1.317681,0.892587,-1.330624,-1.445921,-0.275223,0.502028,-0.526441,Rk,Rk
16,1996,1996,Burlington,Midw,4,SFN,Oyola,Carlos,4/1/1996,B,...,0.641961,-0.823826,0.937874,-0.248841,-1.947371,-0.104710,-1.543258,-0.929851,A,A
17,2006,1990,Fort Lauderdale,FSL,3,NYA,Pimentel,Eddie,4/1/1990,R,...,-1.250870,-0.960130,0.298882,-0.594537,-0.498136,-0.556354,0.298794,-0.562999,A+,A+
18,2006,1989,Salinas,Calif,3,-,Pimentel,Eddie,4/1/1989,R,...,-1.133108,-0.859796,0.210692,-0.189264,-0.617218,-0.479157,-0.472291,-0.094355,A+,A+
19,2050,1996,GCL Rangers,GCL,6,TEX,Seguro,Winston,4/1/1996,R,...,-0.970692,-2.359690,0.970851,-0.892610,-0.448714,-0.446009,1.281872,-1.049104,Rk,Rk
20,2246,1996,Greensboro,SAL,4,NYA,Camfield,Eric,4/1/1996,L,...,0.533235,-0.231147,-0.953024,-1.049993,-0.398286,0.088729,0.739339,-0.610613,A,A+
21,2246,1995,Oneonta,NYPL,5,NYA,Camfield,Eric,4/1/1995,L,...,0.623454,-0.189227,-0.956767,-0.330864,-0.475001,-0.703980,0.501352,0.202876,A-,A+
22,2246,1996,Tampa,FSL,3,NYA,Camfield,Eric,4/1/1996,L,...,0.626091,-0.250603,-0.963550,-1.021689,-0.797685,-0.268435,-1.346790,-0.267669,A+,A+
23,2293,1997,GCL White Sox,GCL,6,CHA,Cordero,Ellery,4/1/1997,R,...,-0.956833,-0.906747,0.374332,0.276037,-0.767803,-0.045984,0.364345,0.210412,Rk,Rk
24,25983,1991,Hamilton,NYPL,5,SLN,Bohrofen,Brent,4/1/1991,R,...,0.567696,-0.486896,-0.874738,0.443154,-0.624449,0.334388,0.570011,-0.094990,A-,A
25,25983,1992,Savannah,SAL,4,SLN,Bohrofen,Brent,4/1/1992,R,...,0.551458,-0.399711,-0.859031,-0.690863,-1.202216,0.106928,1.667641,-0.131203,A,A
26,26698,1993,Helena,Pio,6,MIL,Carter,Chris,4/1/1993,R,...,0.064563,0.332685,1.546497,0.032892,0.639235,0.230633,0.050133,0.080760,Rk,Rk
27,28202,1984,Great Falls,Pio,6,LAN,Estes,Marcus,4/1/1984,L,...,1.184887,0.492113,-0.121480,-1.081734,-0.859994,3.802012,-1.259968,NaN,Rk,A+
28,28202,1985,St. Petersburg,FSL,3,SLN,Estes,Marcus,4/1/1985,L,...,0.482844,0.508035,-0.020546,-0.962921,-1.126022,0.764440,-1.025008,-1.865325,A+,A+
29,29249,1982,Greensboro,SAL,4,NYA,Grove,Trent,4/1/1982,L,...,0.181789,-0.339044,0.901845,-0.718088,-0.991224,-0.311178,0.504915,0.021350,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188950,215703,2018,Azl Padres,Ariz,6,SDN,Almanzar,Luis,4/1/2018,R,...,0.175560,0.052517,0.713780,-0.863933,-0.323458,-0.748779,1.238017,-0.641519,Rk,A
188951,215703,2018,Fort Wayne,Midw,4,SDN,Almanzar,Luis,4/1/2018,R,...,0.272885,-0.231421,0.742405,-0.549137,0.113758,0.691580,0.201010,-0.623541,A,A
188952,215703,2017,Tri-City,Nwst,5,SDN,Almanzar,Luis,4/1/2017,R,...,0.148218,-0.095453,0.662545,-0.516181,0.024737,0.504859,0.407243,0.266652,A-,A
188953,166001,2016,Jacksonville,Sou,2,MIA,Guerrero,Tayron,4/1/2016,R,...,2.651304,-0.017267,-0.107273,-0.976717,-0.957117,-1.201865,-0.792107,-1.676611,AA,AAA
188954,166001,2017,New Orleans,PCL,1,MIA,Guerrero,Tayron,4/1/2017,R,...,2.491651,0.011373,-0.135104,-0.941630,-0.754785,3.377901,-0.760489,NaN,AAA,AAA
188955,166001,2015,El Paso,PCL,1,SDN,Guerrero,Tayron,4/1/2015,R,...,2.703470,-0.045490,-0.067033,-0.891468,-0.717393,-1.119471,-0.734662,-1.613262,AAA,AAA
188956,211970,2018,GCL Phillies West,GCL,6,PHI,Litton,Connor,4/1/2018,R,...,0.505702,1.540394,0.028113,-0.397730,0.060332,0.446712,-1.050797,-0.419536,Rk,Rk
188957,215806,2018,DSL Yankees,Dsl,6,NYA,Chirinos,Roberto,4/1/2018,R,...,0.202645,0.319918,0.982765,1.762294,-0.879805,-0.881911,1.425935,1.229047,Rk,Rk
188958,215806,2018,GCL Yankees West,GCL,6,NYA,Chirinos,Roberto,4/1/2018,R,...,-0.238414,-0.435692,0.631862,-0.273542,-0.652195,0.213545,0.757796,-0.170943,Rk,Rk
188959,216228,2018,Azl Angels,Ariz,6,ANA,Taylor,Cole,4/1/2018,R,...,0.175560,0.786656,0.713780,2.959882,-1.430271,-0.428656,-1.188132,0.425321,Rk,A+
188960,216228,2018,Inland Empire,Calif,3,ANA,Taylor,Cole,4/1/2018,R,...,0.201438,0.834934,0.725604,-0.980925,-0.138988,2.016232,-1.187715,-0.257257,A+,A+
188961,216228,2018,Orem,Pio,6,ANA,Taylor,Cole,4/1/2018,R,...,0.195590,0.656373,0.691312,0.260634,1.447414,0.547827,-0.304423,-0.761246,Rk,A+
188962,216247,2018,Azl Angels,Ariz,6,ANA,Knowles,D'Shawn,4/1/2018,B,...,0.175560,-0.498088,-1.122214,-0.234950,0.166581,-0.229088,0.355781,0.496833,Rk,Rk
188963,216247,2018,Orem,Pio,6,ANA,Knowles,D'Shawn,4/1/2018,B,...,0.195590,-0.503882,-1.176668,0.889379,0.342441,0.616653,-0.132581,1.123677,Rk,Rk
188964,216979,2018,DSL Rangers,DSL,6,TEX,Moss,Keithron,4/1/2018,B,...,0.094595,-0.020892,0.277161,-0.083318,1.223514,0.808840,-0.102733,0.204719,Rk,Rk
188965,217254,2018,DSL Rangers,DSL,6,TEX,Smith,Courtney,4/1/2018,R,...,0.266669,1.144874,-1.513357,-1.409636,0.749530,2.741237,1.444697,-0.571954,Rk,Rk
188966,215911,2018,Azl Royals,Ariz,6,KCA,Hollie,David,4/1/2018,R,...,0.306671,0.419587,-1.122214,0.204339,-0.251749,0.507666,0.429301,-0.075262,Rk,Rk
188967,216906,2018,DSL Royals,DSL,6,KCA,Martinez,Edgar,4/1/2018,R,...,0.008557,-0.437237,0.277161,-1.409636,2.740264,1.509334,1.444697,-1.587604,Rk,Rk
188968,216906,2018,DSL Royals 2,DSL,6,KCA,Martinez,Edgar,4/1/2018,R,...,0.008557,-0.437237,0.277161,-0.199371,-0.243796,-0.158746,-0.213264,0.473349,Rk,Rk
188969,216406,2018,DSL Reds,DSL,6,CIN,Almonte,Sebastian,4/1/2018,R,...,0.266669,0.534235,0.277161,0.082471,-1.087159,0.790724,0.781512,-0.064130,Rk,Rk
188970,216868,2018,DSL Athletics,DSL,6,OAK,Lopez,Hansen,4/1/2018,R,...,-0.077480,0.117890,1.470840,-0.481214,-0.592352,0.971124,-0.213264,-0.839230,Rk,Rk
188971,216639,2018,DSL Dodgers,Dsl,6,LAN,Enrique,Julio,4/1/2018,R,...,0.331737,0.582781,-0.796557,0.003510,0.295590,0.853683,0.254706,0.204869,Rk,Rk
188972,216705,2018,DSL Diamondbacks,DSL,6,ARI,Garcia,Manuel,4/1/2018,R,...,0.094595,0.117890,1.470840,0.049314,-0.207687,-0.023034,1.444697,1.256215,Rk,Rk
188973,216705,2018,DSL Dbacks 2,DSL,6,ARI,Garcia,Manuel,4/1/2018,R,...,0.094595,0.117890,1.470840,-1.409636,-0.160520,-0.837766,-1.569777,-0.420687,Rk,Rk
188974,216983,2018,DSL Red Sox,DSL,6,BOS,Mota,Luis,4/1/2018,L,...,0.094595,-0.437237,0.277161,-1.227268,1.066735,0.372192,-1.208041,-0.466887,Rk,Rk
188975,217075,2018,DSL Giants,DSL,6,SFN,Peralta,Jose,4/1/2018,B,...,0.094595,-0.159674,0.277161,0.331156,-0.295440,0.793111,1.444697,0.281191,Rk,Rk
188976,217121,2018,GCL Red Sox,GCL,6,BOS,Qiang,Justin,4/1/2018,L,...,0.133644,0.140666,1.235612,-0.695779,0.211252,-0.027661,-1.050797,-0.997894,Rk,Rk
188977,217249,2018,DSL Brewers,DSL,6,MIL,Silva,Luis,4/1/2018,R,...,0.266669,0.339940,0.277161,-0.862530,-1.006059,-1.077130,-0.213264,-0.377468,Rk,Rk
188978,217312,2018,DSL Cubs,DSL,6,CHN,Valenzuela,Marco,4/1/2018,L,...,0.266669,0.117890,-0.916517,0.430630,-0.110934,0.542764,0.723844,0.367759,Rk,Rk
188979,217312,2018,DSL Cubs 2,DSL,6,CHN,Valenzuela,Marco,4/1/2018,L,...,0.266669,0.117890,-0.916517,1.707211,0.806408,1.262953,-1.871225,-0.571954,Rk,Rk

In [159]:
final2.to_csv("Resources/working.csv")